### ISSUE TITLE
Signup Confirmation Popup not showing

### ISSUE THREAD

**Issue by varun-singhh** [varun-singhh/vovoca#55]
On successful signup, the confirmation popup is not showing

**Comment by tuanthanh2067** [comment]
Hello, I can work on this issue, can you please assign me?

**Comment by tuanthanh2067** [comment]
For some reason, I still see the confirmation sign up when creating a new account.

**Comment by varun-singhh** [comment]
@tuanthanh2067 I think someone resolved this issue, will be closing this ticket, you can contribute to any other issues.
