### ISSUE TITLE
Add Contributors Section

### ISSUE THREAD

**Issue by varun-singhh** [varun-singhh/vovoca#60]
Since we are having developers section in our web App. 
Requirements:
- Developers should be changed as Team in Navigation Tab
- In the Developers page add new section Contributors below the Developer Sections

**Comment by dyarawilliams** [comment]
Hi @varun-singhh , can you assign this to me, please?

**Comment by dyarawilliams** [comment]
Completed @kaustubhai @varun-singhh  hope you like what I added.
