### ISSUE TITLE
Contact form fonts not matching

### ISSUE THREAD

**Issue by kaustubhai** [varun-singhh/vovoca#63]
## Problem
Font in the the top two fields are not matching with the font-style of textArea as shown in the image in the get in touch form of footer

![image](https://user-images.githubusercontent.com/47121025/136702704-fb928cc3-4e98-4234-94c9-9d92c1ecdbd3.png)

**Comment by SourabhKanade** [comment]
can I solve this?

**Comment by SourabhKanade** [comment]
Done.
